#!/bin/bash

echo "🚀 Deploying HVAC-R Server to Render"
echo "======================================"

# Check if Render CLI is installed
if ! command -v render &> /dev/null; then
    echo "📦 Installing Render CLI..."
    npm install -g render-cli 2>&1 || echo "Note: Install Render CLI manually: npm i -g render"
fi

# Verify build exists
if [ ! -d "dist/server" ]; then
    echo "🔨 Building application..."
    npm run build
fi

echo "✅ Build verified"

# Show deployment options
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 DEPLOYMENT OPTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: Render Dashboard (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect GitHub repository"
echo "4. Configure:"
echo "   • Build Command: npm run build"
echo "   • Start Command: npm run start"
echo "   • Environment: Node"
echo "   • Plan: Standard (recommended for calculations)"
echo ""
echo "5. Add Environment Variables:"
echo "   NODE_ENV=production"
echo "   VITE_SUPABASE_URL=https://rxqflxmzsqhqrzffcsej.supabase.co"
echo "   VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   SUPABASE_DB_PASSWORD=TddR7OpEdrkbbwOE"
echo ""
echo "6. Click 'Create Web Service'"
echo ""

echo "Option 2: Render CLI"
echo "━━━━━━━━━━━━━━━━━━━"
echo "render deploy --spec render.yaml"
echo ""

echo "Option 3: Render Blueprints (Infrastructure as Code)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Go to https://dashboard.render.com/blueprints"
echo "2. Click 'New Blueprint'"
echo "3. Connect GitHub repository"
echo "4. Render will automatically detect render.yaml"
echo "5. Click 'Apply Blueprint'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 DEPLOYMENT CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Server Specifications:"
echo "  • Type: Web Service"
echo "  • Environment: Node.js"
echo "  • Region: us-east (or closest to users)"
echo "  • Plan: Standard (\$25/mo) - for heavy calculations"
echo "  • Min Instances: 1"
echo "  • Max Instances: 3 (auto-scaling)"
echo ""
echo "Health Check:"
echo "  • Path: /"
echo "  • Timeout: 30 seconds"
echo ""
echo "Environment Variables:"
echo "  • NODE_ENV=production"
echo "  • VITE_SUPABASE_URL=https://rxqflxmzsqhqrzffcsej.supabase.co"
echo "  • VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "  • SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "  • SUPABASE_DB_PASSWORD=TddR7OpEdrkbbwOE"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 ENDPOINT REFERENCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After deployment, your server will be available at:"
echo "  https://hvacr-server.onrender.com"
echo ""
echo "API Endpoints:"
echo "  • POST /ai/analyze - AI pattern analysis"
echo "  • POST /ai/patterns/symptom-outcome - Create pattern"
echo "  • GET /ai/patterns - Get patterns"
echo "  • POST /troubleshoot - Troubleshooting workflow"
echo "  • POST /engineering/airflow - Airflow calculations"
echo "  • POST /engineering/delta-t - Delta T calculations"
echo "  • POST /engineering/standard-cycle - Standard cycle calc"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ PRE-DEPLOYMENT CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "[ ] Git repository is up to date"
echo "[ ] All tests pass: npm run test"
echo "[ ] TypeScript compiles: npm run typecheck"
echo "[ ] Build succeeds: npm run build"
echo "[ ] Environment variables tested"
echo "[ ] Supabase connection verified"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 QUICK DEPLOY (Render Dashboard)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open: https://dashboard.render.com"
echo "2. Sign in / Sign up"
echo "3. Click 'New' → 'Web Service'"
echo "4. Select 'Build and deploy from a Git repository'"
echo "5. Choose your GitHub repo"
echo "6. Configure as above"
echo "7. Add environment variables"
echo "8. Click 'Create Web Service'"
echo ""
echo "📝 Your render.yaml file is ready for Blueprint deployments"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 POST-DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Copy your Render server URL"
echo "2. Update Supabase if needed"
echo "3. Test endpoints:"
echo "   curl https://your-render-url.com"
echo "4. Monitor logs in Render dashboard"
echo "5. Set up custom domain (optional)"
echo ""

echo "✅ Deployment guide complete!"
