-- Fix create_job_from_alert to remove invalid column reference (NEW.rule_name)
CREATE OR REPLACE FUNCTION public.create_job_from_alert()
RETURNS TRIGGER AS $$
DECLARE
    v_client_id UUID;
    v_asset_name TEXT;
    v_active_job_exists BOOLEAN;
BEGIN
    -- Only proceed for Critical alerts
    IF NEW.severity != 'critical' THEN
        RETURN NEW;
    END IF;

    -- Get Asset Details
    SELECT client_id, name INTO v_client_id, v_asset_name
    FROM public.assets
    WHERE id = NEW.asset_id;

    -- Check if an active/pending job already exists for this asset
    SELECT EXISTS (
        SELECT 1 FROM public.jobs 
        WHERE asset_id = NEW.asset_id 
        AND status IN ('active', 'pending')
    ) INTO v_active_job_exists;

    -- If no active job, create one!
    IF NOT v_active_job_exists THEN
        INSERT INTO public.jobs (
            user_id, -- Assign to the Admin who owns the client
            job_name,
            client_name, -- Legacy text field
            status,
            notes,
            client_id,
            asset_id,
            created_at
        )
        SELECT 
            c.user_id,
            'CRITICAL: ' || v_asset_name || ' - Alert', -- Removed rule_name, added generic suffix
            cl.name,
            'active',
            'Auto-generated by System based on Critical Alert: ' || NEW.message,
            v_client_id,
            NEW.asset_id,
            NOW()
        FROM public.clients cl
        JOIN public.companies c ON cl.company_id = c.id
        WHERE cl.id = v_client_id;
        
        RAISE NOTICE 'Auto-created job for Asset %', v_asset_name;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
