-- Add FKs to Jobs Table for precise automation
ALTER TABLE public.jobs 
ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS asset_id UUID REFERENCES public.assets(id) ON DELETE SET NULL;

-- Function to Auto-Create Job on Critical Alert
CREATE OR REPLACE FUNCTION public.create_job_from_alert()
RETURNS TRIGGER AS $$
DECLARE
    v_client_id UUID;
    v_asset_name TEXT;
    v_active_job_exists BOOLEAN;
BEGIN
    -- Only proceed for Critical alerts
    IF NEW.severity != 'critical' THEN
        RETURN NEW;
    END IF;

    -- Get Asset Details
    SELECT client_id, name INTO v_client_id, v_asset_name
    FROM public.assets
    WHERE id = NEW.asset_id;

    -- check if we found the asset
    IF v_client_id IS NULL THEN
        RAISE WARNING 'Asset % not found or has no client', NEW.asset_id;
        RETURN NEW;
    END IF;

    -- Check if an active/pending job already exists for this asset
    SELECT EXISTS (
        SELECT 1 FROM public.jobs 
        WHERE asset_id = NEW.asset_id 
        AND status IN ('active', 'pending')
    ) INTO v_active_job_exists;

    -- If no active job, create one!
    IF NOT v_active_job_exists THEN
        INSERT INTO public.jobs (
            user_id, -- We'll need a system user or default to NULL (if flexible) or the Asset Owner? 
            -- Implementing "System" jobs usually requires nullable user_id or a service user. 
            -- For now, let's assume jobs.user_id is NOT NULL (from Jobs.tsx schema check). 
            -- If user_id is required, we might fail. 
            -- Let's check constraints. If user_id is FK to auth.users, we can't easily fake it.
            -- SAFE BET: Use the Client's Owner (Admin) as the creator? Or make user_id nullable?
            -- Strategy: Let's assume we can insert without user_id OR we pick the first Admin of the company.
            
            -- Wait, jobs.user_id referenced auth.users in standard schema. 
            -- Let's grab the Company Owner of the Client.
            job_name,
            client_name, -- Legacy text field
            status,
            notes,
            client_id,
            asset_id,
            created_at
        )
        SELECT 
            c.user_id, -- Assign to the Admin who owns the client
            'CRITICAL: ' || v_asset_name || ' - ' || NEW.rule_name,
            cl.name,
            'active',
            'Auto-generated by System based on Critical Alert: ' || NEW.message,
            v_client_id,
            NEW.asset_id,
            NOW()
        FROM public.clients cl
        JOIN public.companies c ON cl.company_id = c.id
        WHERE cl.id = v_client_id;
        
        RAISE NOTICE 'Auto-created job for Asset %', v_asset_name;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger Definition
DROP TRIGGER IF EXISTS trigger_auto_create_job ON public.rules_alerts;
CREATE TRIGGER trigger_auto_create_job
    AFTER INSERT ON public.rules_alerts
    FOR EACH ROW
    EXECUTE FUNCTION public.create_job_from_alert();
